language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '12'
  - '11'
  - '10'
  - '8'
branches:
  only:
    - master
    - next
    - /^greenkeeper.*$/
script:
  - yarn test
after_success:
  - npx semantic-release
