language: node_js
cache:
  directories:
    - ~/.npm
    - node_modules
notifications:
  email: false
node_js:
  - '9'
  - '8'
  - '6'
branches:
  only:
    - master
    - next
    - /^greenkeeper.*$/
before_install:
  - npm install -g greenkeeper-lockfile@1
before_script: greenkeeper-lockfile-update
script:
  - npm test
after_script: greenkeeper-lockfile-upload
deploy:
  - npm install -g travis-deploy-once@4
  - travis-deploy-once "npm run semantic-release"
